// src/components/OnboardingFlow.vue
<script setup lang="ts">
import ErrorIcon from "./ErrorIcon.vue";
import SuccessIcon from "./SuccessIcon.vue";

import { ref, computed, onMounted } from "vue";
import { initializePaddle, type Paddle } from "@paddle/paddle-js";
import { validateKeycloakToken, parseUserFromToken } from "../utils/auth";
import { PUBLIC_KC_HOSTNAME, PUBLIC_PADDLE_CLIENT_TOKEN, PUBLIC_PADDLE_PRICE_ID } from "astro:env/client";

// Storage key constants
const STORAGE_KEYS = {
  AUTH_TOKEN: "sonacove_auth_token",
  USER_INFO: "sonacove_user_info",
  SUBSCRIPTION_STATUS: "sonacove_subscription_status",
};

type UserInfo = {
    sub: string,
    email: string,
    name: string,
    emailVerified: boolean,
    context: {
      user: {
        subscription_status: string;
        name: string;
        email: string;
      }
    },
}

// State
const currentView = ref("initial");
const userInfo = ref<UserInfo | null>(null);
const accessToken = ref<string | null>(null);
const paddle = ref<Paddle | null>(null);
const discountCode = ref<string>("");
const userFriendlyError = ref("We encountered an unexpected issue.");
const detailedErrorMessage = ref<string | null>(null);
const showDetailedError = ref<boolean>(false);

// Initialize Paddle checkout
async function initializePaddleInstance() {
  try {
    const environment = import.meta.env.PROD ? 'production' : 'sandbox';
    const clientToken = PUBLIC_PADDLE_CLIENT_TOKEN;

    if (!clientToken) {
      throw new Error("Paddle client token is not configured");
    }

    const paddleInstance = await initializePaddle({
      environment,
      token: clientToken,
      eventCallback: (data) => {
        switch (data.name) {
          case "checkout.completed":
            console.log("Checkout completed:", data);
            // Set status to active and show success view
            showSuccessContent(false); // false for 'skipped' means 'active'
            break;
          case "checkout.error":
            console.error("Checkout error:", data);
            handleError(
              "There was a problem with the payment process. Please try again or contact support if the issue persists.",
              data.error || "Paddle checkout error"
            );
            break;
          case "checkout.closed":
            console.log("Checkout closed:", data);
            // User closed checkout, no specific action needed here unless UX requires it
            break;
          case "checkout.loaded":
            console.log("Checkout loaded:", data);
            break;
        }
      },
    });

    return paddleInstance;
  } catch (error) {
    console.error("Error initializing Paddle:", error);
    // This error will be caught by setupPaddleCheckout and then by init if it propagates
    throw error;
  }
}

// Set up Paddle checkout
async function setupPaddleCheckout() {
  try {
    if (!paddle.value) {
      paddle.value = (await initializePaddleInstance()) ?? null;
    }

    if (!paddle.value) {
      // This case should ideally be caught by initializePaddleInstance throwing an error
      throw new Error("Failed to initialize Paddle instance");
    }
  } catch (error) {
    console.error("Error setting up Paddle checkout:", error);
    // This error will be propagated to init() or openPaddleCheckout() and handled there
    throw error;
  }
}

// New function to open the checkout
async function openPaddleCheckout() {
  if (!paddle.value) {
    try {
      await setupPaddleCheckout(); // Ensure Paddle is initialized
    } catch (error) {
      handleError(
        "The subscription service is currently unavailable. Please try again in a few moments.",
        error
      );
      return;
    }
    if (!paddle.value) {
      // Should not happen if setupPaddleCheckout throws as expected
      handleError(
        "The subscription service could not be started. Please try again later.",
        "PaddleInitFailAfterAttempt"
      );
      return;
    }
  }

  try {
    const checkoutConfig = {
      items: [
        {
          priceId: PUBLIC_PADDLE_PRICE_ID,
          quantity: 1,
        },
      ],
      ...(discountCode.value ? { discountCode: discountCode.value } : {}),
      settings: {
        displayMode: 'overlay' as const,
        // frameTarget: "paddle-checkout-container", // For overlay, this might not be strictly needed but good to have if Paddle uses it
        // frameStyle:
        //   "width: 100%; min-height: 400px; background-color: transparent; border: none;",
      },
      ...(userInfo.value?.email
        ? { customer: { email: userInfo.value.email } }
        : {}),
    };

    await paddle.value.Checkout.open(checkoutConfig);
  } catch (error) {
    console.error("Error opening Paddle checkout:", error);
    handleError(
      "Could not open the subscription window. Please check your internet connection or try again shortly.",
      error
    );
  }
}

// Show success content
function showSuccessContent(skipped = false) {
  currentView.value = "success";
  if (userInfo.value) {
    // Ensure local storage is available
    try {
      localStorage.setItem(
        STORAGE_KEYS.SUBSCRIPTION_STATUS,
        skipped ? "trialing" : "active"
      );
    } catch (e) {
      console.error("Failed to write to localStorage:", e);
      handleError(
        "Your session was processed, but we couldn't save your subscription status locally. Please contact support if you see this message again.",
        e
      );
    }
  }
}

// Update registration URL with proper redirect URI
function updateRegistrationUrl() {
  const redirectUri = new URL("/onboarding", window.location.origin);
  // Preserve discount code in redirect
  if (discountCode.value) {
    redirectUri.searchParams.set("discount", discountCode.value);
  }

  const keycloakBaseUrl =
    "https://" +
    PUBLIC_KC_HOSTNAME +
    "/realms/jitsi/protocol/openid-connect";
  const clientId = "jitsi-web";
  const responseType = "token";

  const registrationUrl = `${keycloakBaseUrl}/registrations?client_id=${clientId}&redirect_uri=${encodeURIComponent(
    redirectUri.toString()
  )}&response_type=${responseType}`;

  const userEmail = userInfo.value?.email;
  return userEmail
    ? `${registrationUrl}&login_hint=${encodeURIComponent(userEmail)}`
    : registrationUrl;
}

// Main initialization
async function init() {
  try {
    const urlParams = new URLSearchParams(window.location.search);
    const discountFromQuery = urlParams.get("discount");

    if (discountFromQuery) {
      discountCode.value = discountFromQuery;
    }

    if (window.location.hash) {
      const fragmentParams = new URLSearchParams(
        window.location.hash.substring(1)
      );
      const tokenFromHash = fragmentParams.get("access_token");
      if (tokenFromHash) {
        accessToken.value = tokenFromHash;
        window.location.hash = ""; // Clear the hash
      }
    }

    if (accessToken.value) {
      // Token from Keycloak redirect
      const isAuthenticated = await validateKeycloakToken(
        accessToken.value,
        PUBLIC_KC_HOSTNAME
      );
      if (isAuthenticated) {
        userInfo.value = parseUserFromToken(accessToken.value);
        if (userInfo.value) {
          localStorage.setItem(STORAGE_KEYS.AUTH_TOKEN, accessToken.value);
          localStorage.setItem(
            STORAGE_KEYS.USER_INFO,
            JSON.stringify(userInfo.value)
          );

          const tokenSubStatus =
            userInfo.value?.context?.user?.subscription_status;

          if (tokenSubStatus === "active") {
            localStorage.setItem(STORAGE_KEYS.SUBSCRIPTION_STATUS, "active");
          } else if (tokenSubStatus === "trialing") {
            localStorage.setItem(STORAGE_KEYS.SUBSCRIPTION_STATUS, "trialing");
            // Potentially handle other statuses from token if they exist in your system
          } else {
            // Token doesn't specify a recognized status or has no status info.
            // Check localStorage: if not already 'active', default to 'trialing'.
            // This covers new users or users whose tokens don't have sub info.
            const existingLocalStatus = localStorage.getItem(
              STORAGE_KEYS.SUBSCRIPTION_STATUS
            );
            if (existingLocalStatus !== "active") {
              localStorage.setItem(
                STORAGE_KEYS.SUBSCRIPTION_STATUS,
                "trialing"
              );
            }
          }
        }
        currentView.value = "success";
        await setupPaddleCheckout();
      } else {
        localStorage.removeItem(STORAGE_KEYS.AUTH_TOKEN);
        localStorage.removeItem(STORAGE_KEYS.USER_INFO);
        localStorage.removeItem(STORAGE_KEYS.SUBSCRIPTION_STATUS);
        handleError(
          "Your session appears to be invalid or has expired. Please try creating an account or logging in again.",
          "TokenValidationFalse"
        );
      }
    } else {
      // No token from Keycloak redirect, check local storage
      const storedToken = localStorage.getItem(STORAGE_KEYS.AUTH_TOKEN);
      const storedUserInfoString = localStorage.getItem(STORAGE_KEYS.USER_INFO);

      if (storedToken && storedUserInfoString) {
        const isValid = await validateKeycloakToken(
          storedToken,
          PUBLIC_KC_HOSTNAME
        );
        if (isValid) {
          accessToken.value = storedToken;
          userInfo.value = JSON.parse(storedUserInfoString);
          if (discountFromQuery) {
            discountCode.value = discountFromQuery;
          }

          const storedSubStatus = localStorage.getItem(
            STORAGE_KEYS.SUBSCRIPTION_STATUS
          );
          if (storedSubStatus === "active") {
            currentView.value = "success";
          } else {
            if (storedSubStatus !== "trialing") {
              localStorage.setItem(
                STORAGE_KEYS.SUBSCRIPTION_STATUS,
                "trialing"
              );
            }
            currentView.value = "success";
          }
          await setupPaddleCheckout();
        } else {
          localStorage.removeItem(STORAGE_KEYS.AUTH_TOKEN);
          localStorage.removeItem(STORAGE_KEYS.USER_INFO);
          localStorage.removeItem(STORAGE_KEYS.SUBSCRIPTION_STATUS);
          currentView.value = "initial"; // Go to initial if stored token is invalid
        }
      } else {
        currentView.value = "initial";
        if (discountFromQuery) {
          discountCode.value = discountFromQuery;
        }
      }
    }
  } catch (error) {
    console.error("Error during initialization:", error);
    localStorage.removeItem(STORAGE_KEYS.AUTH_TOKEN);
    localStorage.removeItem(STORAGE_KEYS.USER_INFO);
    localStorage.removeItem(STORAGE_KEYS.SUBSCRIPTION_STATUS);
    handleError(
      "We encountered a problem while setting up your session. Please try refreshing the page or creating an account again.",
      error
    );
  }
}

// Event handlers
function handleReopenPayment() {
  openPaddleCheckout();
}

// Updated error handling function
function handleError(userMessage: string, errorObj: any = null) {
  console.error("User-facing error triggered:", userMessage, errorObj || "");
  userFriendlyError.value =
    userMessage ||
    "An unexpected error occurred. Please try again or contact support if the issue persists.";

  if (errorObj) {
    if (errorObj instanceof Error) {
      detailedErrorMessage.value = `${errorObj.name}: ${errorObj.message}`;
    } else if (typeof errorObj === "string") {
      detailedErrorMessage.value = errorObj;
    } else if (errorObj.message) {
      // For Paddle error objects etc.
      detailedErrorMessage.value = errorObj.message;
    } else {
      detailedErrorMessage.value =
        "Additional error information has been logged to the console.";
    }
  } else {
    detailedErrorMessage.value = null;
  }
  showDetailedError.value = false; // Reset visibility of details
  currentView.value = "error";
}

const isTrialing = computed(() => {
  // Check localStorage availability
  try {
    return (
      localStorage.getItem(STORAGE_KEYS.SUBSCRIPTION_STATUS) === "trialing"
    );
  } catch (e) {
    console.error("Failed to read from localStorage:", e);
    // If localStorage is not accessible, default to a state that doesn't assume trial or active
    // This might mean showing an error or a degraded experience.
    // For now, let's assume not trialing to avoid showing trial-specific UI if we can't verify.
    // This case should ideally be handled more gracefully, perhaps by handleError.
    return false;
  }
});

onMounted(() => {
  // Check for localStorage availability early
  try {
    localStorage.setItem("sonacove_storage_test", "test");
    localStorage.removeItem("sonacove_storage_test");
  } catch (e) {
    console.error("localStorage is not available or write-protected:", e);
    handleError(
      "Your browser's local storage seems to be disabled or full. This is required for the application to function correctly. Please enable it or clear some space and try again.",
      e
    );
    return; // Stop further execution if localStorage isn't working
  }
  init();
});
</script>

<template>
  <div class="container mx-auto px-4 py-12">
    <div
      class="max-w-md mx-auto bg-white rounded-xl shadow-lg overflow-hidden p-8"
    >
      <h1 class="text-2xl font-bold text-center mb-6">
        Welcome to Sonacove Meets
      </h1>

      <!-- Support info - shown on all views except when Paddle is active (handled by overlay) -->
      <div class="text-center mb-6">
        <p class="text-sm text-gray-500">
          Need help? Contact us at
          <a
            href="mailto:support@sonacove.com"
            class="text-primary-600 hover:text-primary-700 underline"
          >
            support@sonacove.com
          </a>
        </p>
      </div>

      <!-- Initial content -->
      <div v-if="currentView === 'initial'" id="initial-content">
        <p class="text-gray-600 mb-6 text-center">
          To get started, please create an account.
        </p>
        <div class="flex flex-col gap-3 justify-center">
          <a
            :href="updateRegistrationUrl()"
            class="px-6 py-3 text-center bg-gradient-to-r from-primary-600 to-accent-600 text-white font-medium rounded-lg hover:opacity-90 transition-all transform hover:scale-[1.02]"
          >
            Create a new account
          </a>
        </div>
      </div>

      <!-- Payment content (Removed as direct view, Paddle opens as overlay) -->
      <!-- This div is targeted by Paddle if frameTarget is set, so keep it if needed by Paddle even for overlay.
           Alternatively, ensure Paddle's overlay doesn't need it, or place it within the success view if actions there trigger Paddle.
           For now, let's ensure it's available but hidden, as Paddle might inject into it.
      -->
      <div class="paddle-checkout-container" style="display: none"></div>

      <!-- Success content -->
      <div
        v-if="currentView === 'success'"
        id="success-content"
        class="text-center"
      >
        <SuccessIcon />
        <h2 class="text-xl font-semibold mt-4">
          Welcome aboard{{
            userInfo?.name ? `, ${userInfo.name.split(" ")[0]}` : ""
          }}!
        </h2>

        <div v-if="isTrialing" class="mt-4">
          <p class="text-gray-600">
            You're now on an unlimited free trial of Sonacove Meets.
          </p>
          <p class="text-gray-600 mt-1">
            Explore all features with 1000 active meeting minutes, then
            subscribe for unlimited access.
          </p>

          <div class="bg-gray-50 rounded-lg p-4 my-6 text-left">
            <p class="font-medium text-gray-800">Account Details:</p>
            <p class="text-gray-600">Email: {{ userInfo?.email }}</p>
            <p class="text-gray-600">Name: {{ userInfo?.name }}</p>
            <p class="text-gray-600">
              Status: Free Trial (1000 minutes included)
            </p>
          </div>

          <div class="space-y-3">
            <button
              @click="handleReopenPayment"
              class="w-full px-6 py-3 bg-gradient-to-r from-primary-600 to-accent-600 text-white font-medium rounded-lg hover:opacity-90 transition-all transform hover:scale-[1.02]"
            >
              Subscribe Now for Full Access
            </button>
            <a
              :href="`/meet/#access_token=${accessToken}`"
              class="block w-full px-6 py-3 bg-white border-2 border-gray-200 text-gray-700 font-medium rounded-lg hover:bg-gray-50 transition-all"
            >
              Continue with Trial
            </a>
          </div>
        </div>

        <div v-else class="mt-4">
          <!-- User is subscribed / active -->
          <p class="text-gray-600">
            Thank you for subscribing to Sonacove Meets. Your account is fully
            activated.
          </p>

          <div class="bg-gray-50 rounded-lg p-4 my-6 text-left">
            <p class="font-medium text-gray-800">Account Details:</p>
            <p class="text-gray-600">Email: {{ userInfo?.email }}</p>
            <p class="text-gray-600">Name: {{ userInfo?.name }}</p>
            <p class="text-gray-600">Status: Active</p>
          </div>

          <a
            :href="`/meet/#access_token=${accessToken}`"
            class="inline-block px-6 py-3 bg-gradient-to-r from-primary-600 to-accent-600 text-white font-medium rounded-lg hover:opacity-90 transition-all transform hover:scale-[1.02]"
          >
            Go to Sonacove Meets
          </a>
        </div>
      </div>

      <!-- Error content -->
      <div
        v-if="currentView === 'error'"
        id="error-content"
        class="text-center"
      >
        <ErrorIcon />
        <h2 class="text-xl font-semibold mt-4">Something went wrong</h2>
        <p class="text-gray-600 mt-2 mb-4">
          {{ userFriendlyError }}
        </p>

        <div
          v-if="detailedErrorMessage"
          class="mb-4 text-sm text-left bg-red-50 p-3 rounded"
        >
          <button
            @click="showDetailedError = !showDetailedError"
            class="text-primary-600 hover:underline mb-2"
          >
            {{ showDetailedError ? "Hide Details" : "Show Technical Details" }}
          </button>
          <div v-if="showDetailedError" class="text-gray-500 break-all">
            <p>For support, please provide the following details:</p>
            <pre class="whitespace-pre-wrap">{{ detailedErrorMessage }}</pre>
          </div>
        </div>

        <div class="mt-6 space-y-4">
          <a
            :href="updateRegistrationUrl()"
            class="block px-6 py-3 bg-gradient-to-r from-primary-600 to-accent-600 text-white font-medium rounded-lg hover:opacity-90 transition-all transform hover:scale-[1.02]"
          >
            Try Creating Account / Login Again
          </a>

          <a
            href="mailto:support@sonacove.com"
            class="block px-6 py-3 text-primary-600 font-medium hover:text-primary-700"
          >
            Contact Support (support@sonacove.com)
          </a>
        </div>
      </div>
    </div>
  </div>
</template>

// src/pages/onboarding/components/OnboardingFlow.tsx
import React, { useState, useEffect, useMemo, useRef } from 'react';
import { initializePaddle, type Paddle } from '@paddle/paddle-js';
import { validateKeycloakToken, parseUserFromToken } from '../../../utils/auth';

import Header from '../../../components/Header';
import { CircleAlert, CircleCheck } from 'lucide-react';
import Button from '../../../components/Button';

interface UserInfo {
  name?: string;
  email?: string;
  context?: {
    user?: {
      subscription_status?: string;
    };
  };
}

// Storage key constants
const STORAGE_KEYS = {
  AUTH_TOKEN: 'sonacove_auth_token',
  USER_INFO: 'sonacove_user_info',
  SUBSCRIPTION_STATUS: 'sonacove_subscription_status',
};

const OnboardingFlow: React.FC = () => {
  // --- STATE MANAGEMENT ---
  const [currentView, setCurrentView] = useState<
    'initial' | 'success' | 'error'
  >('initial');
  const [userInfo, setUserInfo] = useState<UserInfo | null>(null);
  const [accessToken, setAccessToken] = useState<string | null>(null);
  const [discountCode, setDiscountCode] = useState('');
  const [userFriendlyError, setUserFriendlyError] = useState(
    'We encountered an unexpected issue.',
  );
  const [detailedErrorMessage, setDetailedErrorMessage] = useState<
    string | null
  >(null);
  const [showDetailedError, setShowDetailedError] = useState(false);

  const paddle = useRef<Paddle | undefined>(undefined);
  const env = import.meta.env;

  // --- METHODS ---
  const handleError = (userMessage: string, errorObj: any = null) => {
    console.error('User-facing error triggered:', userMessage, errorObj || '');
    setUserFriendlyError(userMessage || 'An unexpected error occurred.');
    if (errorObj) {
      if (errorObj instanceof Error)
        setDetailedErrorMessage(`${errorObj.name}: ${errorObj.message}`);
      else if (typeof errorObj === 'string') setDetailedErrorMessage(errorObj);
      else if (errorObj.message) setDetailedErrorMessage(errorObj.message);
      else
        setDetailedErrorMessage(
          'Additional error information has been logged to the console.',
        );
    } else {
      setDetailedErrorMessage(null);
    }
    setShowDetailedError(false);
    setCurrentView('error');
  };

  const showSuccessContent = (skipped = false) => {
    setCurrentView('success');
    if (userInfo) {
      try {
        localStorage.setItem(
          STORAGE_KEYS.SUBSCRIPTION_STATUS,
          skipped ? 'trialing' : 'active',
        );
      } catch (e) {
        handleError("Couldn't save your subscription status locally.", e);
      }
    }
  };

  const setupPaddleCheckout = async () => {
    try {
      if (!paddle.current) {
        const environment =
          (env.PUBLIC_PADDLE_ENVIRONMENT as 'sandbox' | 'production') ||
          'sandbox';
        const clientToken = env.PUBLIC_PADDLE_CLIENT_TOKEN;
        if (!clientToken)
          throw new Error('Paddle client token is not configured');

        paddle.current = await initializePaddle({
          environment,
          token: clientToken,
          eventCallback: (data) => {
            if (data.name === 'checkout.completed') showSuccessContent(false);
            else if (data.name === 'checkout.error')
              handleError(
                'There was a problem with the payment process.',
                data.error,
              );
          },
        });
      }
    } catch (error) {
      console.error('Error setting up Paddle checkout:', error);
      throw error;
    }
  };

  const openPaddleCheckout = async () => {
    if (!paddle.current) {
      try {
        await setupPaddleCheckout();
      } catch (error) {
        handleError(
          'The subscription service is currently unavailable.',
          error,
        );
        return;
      }
    }
    try {
      await paddle.current?.Checkout.open({
        items: [{ priceId: env.PUBLIC_PADDLE_PRICE_ID, quantity: 1 }],
        ...(discountCode && { discountCode }),
        settings: { displayMode: 'overlay' },
        ...(userInfo?.email && { customer: { email: userInfo.email } }),
      });
    } catch (error) {
      handleError('Could not open the subscription window.', error);
    }
  };

  const updateRegistrationUrl = () => {
    const redirectUri = new URL('/onboarding', window.location.origin);
    if (discountCode) redirectUri.searchParams.set('discount', discountCode);
    const keycloakBaseUrl = `https://${env.PUBLIC_KC_HOSTNAME}/realms/jitsi/protocol/openid-connect`;
    return `${keycloakBaseUrl}/registrations?client_id=jitsi-web&redirect_uri=${encodeURIComponent(
      redirectUri.toString(),
    )}&response_type=token`;
  };

  // --- LIFECYCLE ---
  useEffect(() => {
    const init = async () => {
      try {
        const urlParams = new URLSearchParams(window.location.search);
        const discountFromQuery = urlParams.get('discount');
        if (discountFromQuery) setDiscountCode(discountFromQuery);

        let tokenFromHash: string | null = null;
        if (window.location.hash) {
          const fragmentParams = new URLSearchParams(
            window.location.hash.substring(1),
          );
          tokenFromHash = fragmentParams.get('access_token');
          if (tokenFromHash) {
            setAccessToken(tokenFromHash);
            window.location.hash = '';
          }
        }

        const tokenToValidate =
          tokenFromHash || localStorage.getItem(STORAGE_KEYS.AUTH_TOKEN);

        if (tokenToValidate) {
          const isValid = await validateKeycloakToken(
            tokenToValidate,
            env.PUBLIC_KC_HOSTNAME,
          );
          if (isValid) {
            const parsedUser = parseUserFromToken(tokenToValidate);
            setUserInfo(parsedUser);
            setAccessToken(tokenToValidate);
            localStorage.setItem(STORAGE_KEYS.AUTH_TOKEN, tokenToValidate);
            localStorage.setItem(
              STORAGE_KEYS.USER_INFO,
              JSON.stringify(parsedUser),
            );

            const tokenSubStatus =
              parsedUser?.context?.user?.subscription_status;
            const existingLocalStatus = localStorage.getItem(
              STORAGE_KEYS.SUBSCRIPTION_STATUS,
            );
            if (
              tokenSubStatus === 'active' ||
              existingLocalStatus === 'active'
            ) {
              localStorage.setItem(STORAGE_KEYS.SUBSCRIPTION_STATUS, 'active');
            } else {
              localStorage.setItem(
                STORAGE_KEYS.SUBSCRIPTION_STATUS,
                'trialing',
              );
            }
            setCurrentView('success');
            await setupPaddleCheckout();
          } else {
            localStorage.clear();
            handleError(
              'Your session appears to be invalid or has expired.',
              'TokenValidationFalse',
            );
          }
        } else {
          setCurrentView('initial');
        }
      } catch (error) {
        localStorage.clear();
        handleError(
          'We encountered a problem while setting up your session.',
          error,
        );
      }
    };
    init();
  }, []);

  const isTrialing = useMemo(() => {
    try {
      return (
        localStorage.getItem(STORAGE_KEYS.SUBSCRIPTION_STATUS) === 'trialing'
      );
    } catch (e) {
      return false;
    }
  }, [currentView]);

  return (
    <>
      <Header pageType='landing' />

      <div className='container mx-auto px-4 py-12'>
        <div className='max-w-lg mx-auto bg-white rounded-2xl shadow-lg border border-gray-200 p-8 md:p-12'>
          {/* --- Initial View --- */}
          {currentView === 'initial' && (
            <div className='text-center'>
              <h1 className='text-4xl font-bold text-gray-900 mb-4'>
                Get Started
              </h1>
              <p className='text-lg text-gray-600 mb-8'>
                To begin, please create an account or log in.
              </p>
              <a
                href={updateRegistrationUrl()}
                className='block w-full px-8 py-4 bg-primary-600 text-white font-semibold rounded-full hover:bg-primary-700 transition-transform hover:scale-105 shadow-md'
              >
                Create a New Account
              </a>
              <p className='text-sm text-gray-500 mt-6'>
                Need help? Contact us at{' '}
                <a
                  href='mailto:support@sonacove.com'
                  className='font-medium text-primary-600 hover:underline'
                >
                  support@sonacove.com
                </a>
              </p>
            </div>
          )}

          {/* --- Success View --- */}
          {currentView === 'success' && (
            <div className='text-center'>
              <CircleCheck className='w-16 h-16 mx-auto text-green-500' />
              <h1 className='text-4xl font-bold text-gray-900 mt-6 mb-2'>
                Welcome aboard,{' '}
                {userInfo?.name ? userInfo.name.split(' ')[0] : ''}!
              </h1>

              {isTrialing ? (
                <>
                  <p className='text-lg text-gray-600'>
                    You're now on our unlimited free trial.
                  </p>
                  <div className='bg-gray-50 rounded-xl p-6 my-8 text-left space-y-2 border'>
                    <p className='font-semibold text-gray-800'>Your Account:</p>
                    <p className='text-gray-600'>
                      <strong>Email:</strong> {userInfo?.email}
                    </p>
                    <p className='text-gray-600'>
                      <strong>Status:</strong> Free Trial (1000 minutes)
                    </p>
                  </div>
                  <div className='space-y-4'>
                    <Button
                      onClick={openPaddleCheckout}
                      variant='primary'
                      className='w-full'
                    >
                      Subscribe Now for Full Access
                    </Button>
                    <Button
                      onClick={() =>
                        (window.location.href = `/meet/#access_token=${accessToken}`)
                      }
                      variant='secondary'
                      className='w-full'
                    >
                      Continue with Trial
                    </Button>
                  </div>
                </>
              ) : (
                <>
                  <p className='text-lg text-gray-600'>
                    Your account is fully activated.
                  </p>
                  <div className='bg-gray-50 rounded-xl p-6 my-8 text-left space-y-2 border'>
                    <p className='font-semibold text-gray-800'>Your Account:</p>
                    <p className='text-gray-600'>
                      <strong>Email:</strong> {userInfo?.email}
                    </p>
                    <p className='text-gray-600'>
                      <strong>Status:</strong> Active
                    </p>
                  </div>
                  <Button
                    onClick={() =>
                      (window.location.href = `/meet/#access_token=${accessToken}`)
                    }
                    variant='primary'
                    className='w-full'
                  >
                    Go to Sonacove Meets
                  </Button>
                </>
              )}
            </div>
          )}

          {/* --- Error View --- */}
          {currentView === 'error' && (
            <div className='text-center'>
              <CircleAlert className='w-16 h-16 mx-auto text-red-500' />
              <h1 className='text-4xl font-bold text-gray-900 mt-6 mb-2'>
                Something went wrong
              </h1>
              <p className='text-lg text-gray-600 mb-6'>{userFriendlyError}</p>

              {detailedErrorMessage && (
                <div className='mb-6 text-sm text-left bg-red-50 p-4 rounded-lg border border-red-200'>
                  <button
                    onClick={() => setShowDetailedError(!showDetailedError)}
                    className='font-semibold text-primary-600 hover:underline mb-2'
                  >
                    {showDetailedError
                      ? 'Hide Technical Details'
                      : 'Show Technical Details'}
                  </button>
                  {showDetailedError && (
                    <pre className='mt-2 text-xs text-gray-600 whitespace-pre-wrap bg-white p-2 rounded'>
                      {detailedErrorMessage}
                    </pre>
                  )}
                </div>
              )}

              <div className='mt-8 space-y-4'>
                <Button
                  onClick={() => {
                    window.location.href = updateRegistrationUrl();
                  }}
                  variant='primary'
                  className='w-full'
                >
                  Try Again
                </Button>
                <a
                  href='mailto:support@sonacove.com'
                  className='block text-center text-primary-600 font-medium hover:underline'
                >
                  Contact Support
                </a>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
};

export default OnboardingFlow;
